services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - dbdata:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  dbdata:
