services:
  database:
    image: postgres:16-alpine
    restart: always
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      BASEPATH: ${BASEPATH}
    volumes:
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./logs/database:/var/log/postgresql
      - ./data/database:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -p ${DB_PORT}
  web:
    image: patrickrios/aula-virtual:latest
    restart: always
    container_name: aula-virtual-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - database
