-- AlterTable
ALTER TABLE "cursos" ADD COLUMN     "acompanamiento" JSONB DEFAULT '[]',
ADD COLUMN     "ayudas_becas" JSONB DEFAULT '[]',
ADD COLUMN     "certificaciones" JSONB DEFAULT '[]',
ADD COLUMN     "director" JSONB DEFAULT '{}',
ADD COLUMN     "empresas_alumnos" JSONB DEFAULT '[]',
ADD COLUMN     "faqs" JSONB DEFAULT '[]',
ADD COLUMN     "herramientas" JSONB DEFAULT '[]',
ADD COLUMN     "mostrar_acompanamiento" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_admision" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_becas" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_beneficios" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_certificaciones" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_director" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_empresas" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_faqs" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_herramientas" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_incluye" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_metodologia" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_objetivos" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_perfil" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_por_que_estudiar" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_por_que_nosotros" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_rankings" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_relacionados" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mostrar_salidas" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "perfil_estudiante" TEXT,
ADD COLUMN     "por_que_estudiar" JSONB DEFAULT '[]',
ADD COLUMN     "por_que_nosotros" JSONB DEFAULT '{}',
ADD COLUMN     "proceso_admision" JSONB DEFAULT '[]',
ADD COLUMN     "programas_relacionados" JSONB DEFAULT '[]',
ADD COLUMN     "rankings" JSONB DEFAULT '[]',
ADD COLUMN     "requisitos_admision" JSONB DEFAULT '[]',
ADD COLUMN     "salidas_profesionales" JSONB DEFAULT '[]',
ADD COLUMN     "testimonios" JSONB DEFAULT '[]',
ADD COLUMN     "titulo_admision" TEXT,
ADD COLUMN     "titulo_certificaciones" TEXT,
ADD COLUMN     "titulo_plan_estudios" TEXT,
ADD COLUMN     "titulo_programa" TEXT,
ADD COLUMN     "titulo_salidas" TEXT;

-- AlterTable
ALTER TABLE "leads_portada" ADD COLUMN     "ciudad" TEXT,
ADD COLUMN     "detalle" TEXT,
ADD COLUMN     "pais" TEXT,
ADD COLUMN     "profesion" TEXT,
ALTER COLUMN "escuela" DROP NOT NULL,
ALTER COLUMN "modalidad" DROP NOT NULL;
